name: 'Prepare signing'
description: 'Prepare signing of the iOS application'
inputs:
  appStoreConnectPrivateKey:
    description: 'App Store Connect private key with proper rights'
    required: true
  keyID:
    description: 'Identifier of the private key'
    required: true
  issuerID:
    description: 'Issuer identifier'
    required: true
  keychainName:
    description: 'Id of the newly created temporary kechain'
    required: true
    default: 'signing.ios'
  keychainPassword:
    description: 'Password of the newly created temporary kechain'
    required: true
    default: 'signing.ios'
  base64P12File:
    description: 'Base64 encoded .p12 signing cert with private key'
    required: true
  base64ExtensionP12File:
    description: 'Base64 encoded .p12 signing cert with private key, for extension'
    required: true
  p12Password:
    description: 'Password of the .p12 file'
    required: true
  bundleIdentifier:
    description: 'Bundle identifier of the application'
    required: true
  signType:
    description: 'E.g.: IOS_APP_DEVELOPMENT, IOS_APP_STORE etc.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'shield'
  color: 'orange'
